server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: app-microservices_config-server
          uri: https://github.com/MVAZBAU/app-microservices
          search-paths: config-data
  application:
    name: config-service